name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    permissions:
       id-token: write
       contents: read
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false

      - name: Install Dependencies
        run: npm install

      - name: Build Project with Environment Variables
        run: |
          NODE_ENV=production \
          VITE_AWS_ACCESS_KEY_ID_INDIA=${{ secrets.VITE_AWS_ACCESS_KEY_ID_INDIA }} \
          VITE_AWS_SECRET_ACCESS_KEY_INDIA=${{ secrets.VITE_AWS_SECRET_ACCESS_KEY_INDIA }} \
          VITE_AWS_REGION_INDIA=${{ secrets.VITE_AWS_REGION_INDIA }} \
          VITE_AWS_ACCESS_KEY_ID_USA=${{ secrets.VITE_AWS_ACCESS_KEY_ID_USA }} \
          VITE_AWS_SECRET_ACCESS_KEY_USA=${{ secrets.VITE_AWS_SECRET_ACCESS_KEY_USA }} \
          VITE_AWS_REGION_USA=${{ secrets.VITE_AWS_REGION_USA }} \
          VITE_GOOGLE_CLIENT_ID=${{ secrets.VITE_GOOGLE_CLIENT_ID }} \
          npm run build

      - name: Get Id Token
        uses: actions/github-script@v6
        id: idtoken
        with:
           script: |
               const coredemo = require('@actions/core')
               return await coredemo.getIDToken()
           result-encoding: string

      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_ICY_MUD_03C9DD41E }}
          action: "upload"
          app_location: "/"  
          api_location: ""  
          output_location: "dist"  
          github_id_token: ${{ steps.idtoken.outputs.result }}

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          action: "close"
